services:
  api:
    build:
      context: ./
      dockerfile: api.dockerfile
    env_file:
      - .env
    command: python /api/main.py
    volumes:
      - ../api:/api
    depends_on:
      - database
    ports:
      - 8000:8000
  database:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
volumes:
  postgres-db-volume: