services:
  api:
    build:
      context: ../
      dockerfile: ./.docker/app.dockerfile
    env_file:
      - .dev.env
    command: python app/main.py
    volumes:
      - ../server:/usr/src/server
    environment:
      PYTHONPATH: /usr/src/server
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@postgres-db:5432/dev
    depends_on:
      - postgres-db
    ports:
      - 8000:8000
  postgres-db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dev
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
volumes:
  postgres-db-volume: